#%RAML 1.0 Library
usage: Defines standard structure of a customer


types:
  customer:
    properties:
      id?:
        type: string
      firstname:
        type: string
      lastname:
        type: string
      address?:
        type: string
